version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    networks:
      - app_network

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_COMMIT: ${SOURCE_COMMIT:-unknown}
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      SESSION_SECRET: ${SESSION_SECRET}
      STEAM_API_KEY: ${STEAM_API_KEY}
      STEAM_CALLBACK_URL: ${STEAM_CALLBACK_URL}
      CLOUDFLARE_ANALYTICS_TOKEN: ${CLOUDFLARE_ANALYTICS_TOKEN}
    ports:
      - "3000:3000"
    networks:
      - app_network
    command: ["./start.sh"]

networks:
  app_network: